### ISSUE TITLE
Starts numbering at 10 instead of 0

### ISSUE THREAD

**Issue by tika-iteratec** [tum-gis/cesium-terrain-builder-docker#18]
Hi,

when I follow the instructions I get the following structure:
```
terrain/
|-- 10
|   `-- 1113
|-- 11
|-- 12
|-- 13
|-- 14
|-- 15
|-- 16
|-- 17
|-- 18
`-- layer.json
```
How can I fix the numbering?

I guess that's the reason why the terrain is not displayed.

Thanks for any help

**Comment by BWibo** [comment]
Hey there,
this repo hosts the Docker image for CesiumTerrainBuilder. I cannot provide support for the application itself, because I did not develop it. Closing, as this does not appear to be an issue related to the Docker implementation. Try to find help in the [application repo](https://github.com/geo-data/cesium-terrain-builder).

If you post an issue there, I suggest to provide a much more detailed report on the problem you faced and if possible a data sample. It will most likely be impossible to help you based on the information you provided above.
All I can see from the folder structure: The layers from 0-9 are missing.
