### ISSUE TITLE
Failed to obtain terrain tile X: 1 Y: 0 Level: 0.

### ISSUE THREAD

**Issue by DarcyLeeDuni** [tum-gis/cesium-terrain-builder-docker#8]
the url is current(exist 0/0/0.terrain and 0/1/0.terrain), but it seems to failed in the createQuantizedMeshTerrainData method which vertexCount is very large and more than the terrain size. An error occurs in this line.

**Comment by fnicollet** [comment]
Hello,

Had the same issue, these threads might help:
https://github.com/geo-data/cesium-terrain-builder/issues/62
https://github.com/geo-data/cesium-terrain-builder/issues/16

In my case, I changed my Apache configuration to add:
```
AddType application/octet-stream .terrain
AddEncoding gzip .terrain
```
Then deleted my browser's cache. Make sure the browser requests the terrain tiles in the developper tools, in the Network tab.
This fork of cesium-terrain-builder creates the tiles at the 0/1 levels so that Cesium can load them.
If you are not using this fork, you need to use the "cesium terrain server":
https://github.com/geo-data/cesium-terrain-server
Which will serve the dummy tiles (but I advise you to use this fork instead so that you can produce quantified mesh

Hope it helps,

**Comment by DarcyLeeDuni** [comment]
Thank you, I also found that the problem is that the program USES GZIP by default, so I cloned the source code and changed it to not use GZIP. But your solution should be more perfect, and I'll give it a try. Thanks again.

**Comment by BWibo** [comment]
Thx for your comment @fnicollet . 
@DarcyLeeDuni : Check out this: https://github.com/tum-gis/3dcitydb-docker-compose/tree/cesium-terrain-server/web-map+cesium-terrain-server
you will find a Docker file for hosting CesiumTerrainServer there. It is still work in progress and the documentation is not fully complete, but you should be able to fill the gaps yourself.

Closing, as this is an issue regarding the provisioning of terrain tiles and not their creation, that cesium-terrain-builder is good for.
